class Commands:
    LEECH = "leech"
    PURGE = "purge"
    PAUSEALL = "pauseall"
    RESUMEALL = "resumeall"
    STATUS = "stats"
    SETTINGS = "settings"
    EXEC = "exec"
    UPLOAD = "upload"
    YTDL = "ytdl"
    PYTDL = "pytd"
    ABOUT = "abt"
    GETLOGS = "log"
    SERVER = "stat"
    USERSETTINGS = "uset"
    INSTADL = "instadl"
