class Commands:
    LEECH = "leech1"
    PURGE = "purge"
    PAUSEALL = "pauseall"
    RESUMEALL = "resumeall"
    STATUS = "status"
    SETTINGS = "settings"
    EXEC = "exec"
    UPLOAD = "upload"
    YTDL = "ytdl1"
    PYTDL = "pytdl"
    ABOUT = "about"
    GETLOGS = "getlogs"
    SERVER = "stats"
    USERSETTINGS = "usettings"
    INSTADL = "instadl"
